-- MySQL Script generated by MySQL Workbench
-- 06/29/14 00:21:06
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lovely_ads
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `lovely_ads` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `lovely_ads` ;

-- -----------------------------------------------------
-- Table `lovely_ads`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lovely_ads`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `id_facebook` VARCHAR(255) NULL,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `publication` TINYINT NOT NULL DEFAULT 0 COMMENT '0: let the publication be set by the review publication' /* comment truncated */ /*1: only the user can see his reviews
2: only user's friends can see his reviews
3: everyone can see his reviews*/,
  `status` TINYINT NOT NULL DEFAULT 1,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `lovely_ads`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lovely_ads`.`categorie` (
  `id_categorie` INT NOT NULL AUTO_INCREMENT,
  `name_categorie` TEXT NULL,
  PRIMARY KEY (`id_categorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lovely_ads`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lovely_ads`.`product` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `ean_code` VARCHAR(255) NULL,
  `name` VARCHAR(255) NULL,
  `id_categorie` INT NULL,
  `brand` VARCHAR(255) NULL,
  `link_image` TEXT NULL,
  PRIMARY KEY (`id_product`),
  INDEX `id_categorie_idx` (`id_categorie` ASC),
  CONSTRAINT `id_categorie`
    FOREIGN KEY (`id_categorie`)
    REFERENCES `lovely_ads`.`categorie` (`id_categorie`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `lovely_ads`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lovely_ads`.`review` (
  `id_review` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_product` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `rate` SMALLINT NOT NULL,
  `publication` TINYINT NOT NULL COMMENT '1: only the user can see his reviews' /* comment truncated */ /*2: only user's friends can see his reviews
3: everyone can see his reviews*/,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id_review`, `id_user`, `id_product`),
  INDEX `fk_review_user_idx` (`id_user` ASC),
  INDEX `fk_review_product1_idx` (`id_product` ASC),
  CONSTRAINT `fk_review_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `lovely_ads`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_product1`
    FOREIGN KEY (`id_product`)
    REFERENCES `lovely_ads`.`product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `lovely_ads`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lovely_ads`.`comment` (
  `id_comment` INT NOT NULL AUTO_INCREMENT,
  `id_review` INT NOT NULL,
  `id_user` INT NOT NULL,
  `content` TEXT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id_comment`, `id_review`, `id_user`),
  INDEX `fk_comment_review1_idx` (`id_review` ASC),
  INDEX `fk_comment_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_comment_review1`
    FOREIGN KEY (`id_review`)
    REFERENCES `lovely_ads`.`review` (`id_review`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `lovely_ads`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `lovely_ads`.`edition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lovely_ads`.`edition` (
  `id_edition` INT NOT NULL AUTO_INCREMENT,
  `id_review` INT NOT NULL,
  `content` TEXT NOT NULL,
  `mood` TINYINT NOT NULL COMMENT '0: neutral' /* comment truncated */ /*1: happy
2: content
3: astone
4: fear
5: cry
6: angry*/,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id_edition`, `id_review`),
  INDEX `fk_edition_review1_idx` (`id_review` ASC),
  CONSTRAINT `fk_edition_review1`
    FOREIGN KEY (`id_review`)
    REFERENCES `lovely_ads`.`review` (`id_review`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `lovely_ads`.`user_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lovely_ads`.`user_has_user` (
  `id_match` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_facebook_friend` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_match`),
  CONSTRAINT `fk_user_has_user_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `lovely_ads`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `lovely_ads`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lovely_ads`.`customer` (
  `id_customer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NULL,
  `api_token` VARCHAR(32) NULL,
  PRIMARY KEY (`id_customer`),
  UNIQUE INDEX `id_cutomer_UNIQUE` (`id_customer` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `lovely_ads`.`customer_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lovely_ads`.`customer_product` (
  `id_customer` INT NOT NULL,
  `id_product` INT NOT NULL,
  INDEX `id_product_idx` (`id_product` ASC),
  PRIMARY KEY (`id_customer`, `id_product`),
  CONSTRAINT `id_product`
    FOREIGN KEY (`id_product`)
    REFERENCES `lovely_ads`.`product` (`id_product`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_customer`
    FOREIGN KEY (`id_customer`)
    REFERENCES `lovely_ads`.`customer` (`id_customer`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
